services:
  api:
    image: mhwilds-api
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/api
    environment:
      FLASK_DEBUG: 1
    command: flask run -h 0.0.0.0

  flask_db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - flask_db

volumes:
  pgdata: