services:
  api:
    image: nimgurung/mhwilds-api/1.0
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/api
    environment:
      SQLALCHEMY_DATABASE_URI_DEV: ${DB_URL}
      FLASK_DEBUG: 1
    depends_on:
      - flask_db

  flask_db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - flask_db

volumes:
  pgdata: