"""defense field changed back to not nullable

Revision ID: 080c6345b830
Revises: f2a3c213c897
Create Date: 2025-04-08 19:47:01.352070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080c6345b830'
down_revision = 'f2a3c213c897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('armour_model', schema=None) as batch_op:
        batch_op.alter_column('defense',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('armour_model', schema=None) as batch_op:
        batch_op.alter_column('defense',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
