"""removed link from armour to skillrankmodel

Revision ID: 32f2d27b13ef
Revises: a1660c075c14
Create Date: 2025-03-29 18:09:32.529171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f2d27b13ef'
down_revision = 'a1660c075c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_rank_model', schema=None) as batch_op:
        batch_op.drop_constraint('skill_rank_model_armour_id_fkey', type_='foreignkey')
        batch_op.drop_column('armour_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_rank_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('armour_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('skill_rank_model_armour_id_fkey', 'armour_model', ['armour_id'], ['id'])

    # ### end Alembic commands ###
