"""description to charmModel

Revision ID: 3a21ba0de3dc
Revises: 976ddff7345b
Create Date: 2025-05-03 10:02:13.043280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a21ba0de3dc'
down_revision = '976ddff7345b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charm_rank_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charm_rank_model', schema=None) as batch_op:
        batch_op.drop_column('desc')

    # ### end Alembic commands ###
