"""Initial migration.

Revision ID: 6d65f8c5b347
Revises: 
Create Date: 2025-03-26 20:24:01.832309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d65f8c5b347'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slot_model', schema=None) as batch_op:
        batch_op.drop_constraint('slot_model_armour_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'armour_model', ['armour_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slot_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('slot_model_armour_id_fkey', 'armour_model', ['armour_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
