"""resistances model

Revision ID: 789864b000b3
Revises: 950085a5f3cd
Create Date: 2025-04-08 19:08:24.125602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789864b000b3'
down_revision = '950085a5f3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resistances_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fire', sa.Integer(), nullable=False),
    sa.Column('water', sa.Integer(), nullable=False),
    sa.Column('ice', sa.Integer(), nullable=False),
    sa.Column('thunder', sa.Integer(), nullable=False),
    sa.Column('dragon', sa.Integer(), nullable=False),
    sa.Column('armour_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['armour_id'], ['armour_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resistances_model')
    # ### end Alembic commands ###
