"""association table

Revision ID: 950085a5f3cd
Revises: 32f2d27b13ef
Create Date: 2025-03-30 14:33:59.320966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950085a5f3cd'
down_revision = '32f2d27b13ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('armour_skills',
    sa.Column('armour_id', sa.Integer(), unique=False, nullable=True),
    sa.Column('skill_id', sa.Integer(), unique=False, nullable=True),
    sa.ForeignKeyConstraint(['armour_id'], ['armour_model.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_rank_model.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('armour_skills')
    # ### end Alembic commands ###
