"""charm models added

Revision ID: 976ddff7345b
Revises: 080c6345b830
Create Date: 2025-04-27 14:36:45.455708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976ddff7345b'
down_revision = '080c6345b830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charm_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('charm_rank_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.Integer(), nullable=False),
    sa.Column('charm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['charm_id'], ['charm_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charm_skill_ranks',
    sa.Column('charm_rank_model', sa.Integer(), nullable=True),
    sa.Column('skill_rank_model', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charm_rank_model'], ['charm_rank_model.id'], ),
    sa.ForeignKeyConstraint(['skill_rank_model'], ['skill_rank_model.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charm_skill_ranks')
    op.drop_table('charm_rank_model')
    op.drop_table('charm_model')
    # ### end Alembic commands ###
