"""+decoration model, and modified charm/skill associate table column name

Revision ID: 9984fc102658
Revises: 3a21ba0de3dc
Create Date: 2025-05-03 12:19:16.610465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9984fc102658'
down_revision = '3a21ba0de3dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decoration_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('rarity', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('deco_skill_ranks',
    sa.Column('decoration_id', sa.Integer(), nullable=True),
    sa.Column('skill_rank_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['decoration_id'], ['decoration_model.id'], ),
    sa.ForeignKeyConstraint(['skill_rank_id'], ['skill_rank_model.id'], )
    )
    with op.batch_alter_table('charm_skill_ranks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charm_rank_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('skill_rank_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('charm_skill_ranks_charm_rank_model_fkey', type_='foreignkey')
        batch_op.drop_constraint('charm_skill_ranks_skill_rank_model_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'skill_rank_model', ['skill_rank_id'], ['id'])
        batch_op.create_foreign_key(None, 'charm_rank_model', ['charm_rank_id'], ['id'])
        batch_op.drop_column('skill_rank_model')
        batch_op.drop_column('charm_rank_model')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charm_skill_ranks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charm_rank_model', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('skill_rank_model', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('charm_skill_ranks_skill_rank_model_fkey', 'skill_rank_model', ['skill_rank_model'], ['id'])
        batch_op.create_foreign_key('charm_skill_ranks_charm_rank_model_fkey', 'charm_rank_model', ['charm_rank_model'], ['id'])
        batch_op.drop_column('skill_rank_id')
        batch_op.drop_column('charm_rank_id')

    op.drop_table('deco_skill_ranks')
    op.drop_table('decoration_model')
    # ### end Alembic commands ###
