"""link armour model and skill model

Revision ID: b8c6cdb3c9be
Revises: 6d65f8c5b347
Create Date: 2025-03-29 17:23:01.467411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c6cdb3c9be'
down_revision = '6d65f8c5b347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('armour_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'armour_model', ['armour_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('armour_id')

    # ### end Alembic commands ###
