"""defense field added

Revision ID: f2a3c213c897
Revises: 789864b000b3
Create Date: 2025-04-08 19:37:56.934322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a3c213c897'
down_revision = '789864b000b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('armour_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defense', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('armour_model', schema=None) as batch_op:
        batch_op.drop_column('defense')

    # ### end Alembic commands ###
